// sample_recommended_providers.dart

import 'package:scooby_app_new/models/service_provider.dart';

final List<ServiceProvider> sampleRecommendedProviders = [
  // 3 Veterinarians
  ServiceProvider(
    id: 1,
    userId: 'user_001',
    name: 'Dr. Chamari Silva',
    phoneNo: '+94 77 123 4567',
    email: 'chamari.silva.vet@gmail.com',
    city: 'Colombo',
    role: 'Veterinarian',
    profileImageUrl: 'https://example.com/images/chamari_silva.jpg',
    galleryImages: [
      'https://example.com/images/vet_gallery_1.jpg',
      'https://example.com/images/vet_gallery_2.jpg',
      'https://example.com/images/vet_gallery_3.jpg',
    ],
    qualificationUrl: '',
    verificationUrl: '',
    clinicOrSalonName: 'Healthy Paws Veterinary Clinic',
    clinicOrSalonAddress: '123 Galle Road, Colombo',
    aboutClinicSalon: 'Caring for pets with love and professionalism.',
    experience: '8',
    serviceDescription: 'General health checkups, vaccinations, emergency care.',
    pricingDetails: '',
    consultationFee: '1500 LKR',
    groomingServices: [],
    comfortableWith: ['Dogs', 'Cats'],
    availableTimes: 'Mon-Fri 9am-5pm',
    dislikes: '',
    rate: '4.8',
    notes: '',
  ),
  ServiceProvider(
    id: 2,
    userId: 'user_002',
    name: 'Dr. Nimal Perera',
    phoneNo: '+94 71 234 5678',
    email: 'nimal.perera.vet@gmail.com',
    city: 'Gampaha', 
    role: 'Veterinarian',
    profileImageUrl: 'https://example.com/images/nimal_perera.jpg',
    galleryImages: [
      'https://example.com/images/vet2_gallery_1.jpg',
      'https://example.com/images/vet2_gallery_2.jpg',
      'https://example.com/images/vet2_gallery_3.jpg',
    ],
    qualificationUrl: '',
    verificationUrl: '',
    clinicOrSalonName: 'Gampaha Animal Care',
    clinicOrSalonAddress: '45 Kandy Road, Gampaha',
    aboutClinicSalon: 'Expert care for your beloved pets.',
    experience: '12',
    serviceDescription: 'Surgery, diagnostics, dental care, vaccinations.',
    pricingDetails: '',
    consultationFee: '2000 LKR',
    groomingServices: [],
    comfortableWith: ['Dogs', 'Cats', 'Birds'],
    availableTimes: 'Mon-Sat 8am-6pm',
    dislikes: '',
    rate: '4.9',
    notes: '',
  ),
  ServiceProvider(
    id: 3,
    userId: 'user_003',
    name: 'Dr. Anusha Fernando',
    phoneNo: '+94 77 345 6789',
    email: 'anusha.fernando.vet@gmail.com',
    city: 'Anuradhapura',
    role: 'Veterinarian',
    profileImageUrl: 'https://example.com/images/anusha_fernando.jpg',
    galleryImages: [
      'https://example.com/images/vet3_gallery_1.jpg',
      'https://example.com/images/vet3_gallery_2.jpg',
    ],
    qualificationUrl: '',
    verificationUrl: '',
    clinicOrSalonName: 'Happy Tails Vet Clinic',
    clinicOrSalonAddress: '89 Marine Drive, Anuradhapura',
    aboutClinicSalon: 'Passionate about pet health and wellness.',
    experience: '6',
    serviceDescription: 'Wellness exams, vaccination, microchipping.',
    pricingDetails: '',
    consultationFee: '1800 LKR',
    groomingServices: [],
    comfortableWith: ['Dogs', 'Cats', 'Rabbits'],
    availableTimes: 'Tue-Sat 9am-5pm',
    dislikes: '',
    rate: '4.7',
    notes: '',
  ),

  // 2 Pet Groomers
  ServiceProvider(
    id: 4,
    userId: 'user_004',
    name: 'Lalitha Wickramasinghe',
    phoneNo: '+94 76 123 4567',
    email: 'lalitha.groomer@gmail.com',
    city: 'Galle', // Changed from Colombo
    role: 'Pet Groomer',
    profileImageUrl: 'https://example.com/images/lalitha_wickramasinghe.jpg',
    galleryImages: [
      'https://example.com/images/groomer1_gallery_1.jpg',
      'https://example.com/images/groomer1_gallery_2.jpg',
      'https://example.com/images/groomer1_gallery_3.jpg',
    ],
    qualificationUrl: '',
    verificationUrl: '',
    clinicOrSalonName: 'Pawfect Grooming Salon',
    clinicOrSalonAddress: '12 Flower Street, Galle',
    aboutClinicSalon: 'Grooming with care and style.',
    experience: '5',
    serviceDescription: 'Full grooming, nail trimming, ear cleaning.',
    pricingDetails: 'Full grooming from 2500 LKR',
    consultationFee: '',
    groomingServices: ['Full Grooming', 'Nail Trim', 'Ear Cleaning'],
    comfortableWith: ['Dogs', 'Cats'],
    availableTimes: 'Mon-Fri 10am-6pm',
    dislikes: '',
    rate: '4.6',
    notes: '',
  ),
  ServiceProvider(
    id: 5,
    userId: 'user_005',
    name: 'Kamal Perera',
    phoneNo: '+94 77 987 6543',
    email: 'kamal.groomer@gmail.com',
    city: 'Colombo',
    role: 'Pet Groomer',
    profileImageUrl: 'https://example.com/images/kamal_perera.jpg',
    galleryImages: [
      'https://example.com/images/groomer2_gallery_1.jpg',
      'https://example.com/images/groomer2_gallery_2.jpg',
    ],
    qualificationUrl: '',
    verificationUrl: '',
    clinicOrSalonName: 'Groom & Glow',
    clinicOrSalonAddress: '77 Lake Avenue, Colombo',
    aboutClinicSalon: 'Professional pet grooming services.',
    experience: '7',
    serviceDescription: 'Bath, haircut, styling, flea treatment.',
    pricingDetails: 'Prices start from 2000 LKR',
    consultationFee: '',
    groomingServices: ['Bath', 'Haircut', 'Flea Treatment'],
    comfortableWith: ['Dogs', 'Cats'],
    availableTimes: 'Tue-Sat 9am-5pm',
    dislikes: '',
    rate: '4.7',
    notes: '',
  ),

  // 3 Pet Sitters
  ServiceProvider(
    id: 6,
    userId: 'user_006',
    name: 'Samantha Jayasinghe',
    phoneNo: '+94 71 654 3210',
    email: 'samantha.sitter@gmail.com',
    city: 'Colombo',
    role: 'Pet Sitter',
    profileImageUrl: 'https://example.com/images/samantha_jayasinghe.jpg',
    galleryImages: [
      'https://example.com/images/sitter1_gallery_1.jpg',
      'https://example.com/images/sitter1_gallery_2.jpg',
      'https://example.com/images/sitter1_gallery_3.jpg',
    ],
    qualificationUrl: '',
    verificationUrl: '',
    clinicOrSalonName: 'Home Pet Sitting',
    clinicOrSalonAddress: 'Colombo',
    aboutClinicSalon: 'Loving care for your pets at home.',
    experience: '4',
    serviceDescription: 'Day care, overnight stays, feeding.',
    pricingDetails: 'Hourly rate: 800 LKR',
    consultationFee: '',
    groomingServices: [],
    comfortableWith: ['Dogs', 'Cats', 'Birds'],
    availableTimes: 'Mon-Sun Flexible',
    dislikes: '',
    rate: '4.9',
    notes: '',
  ),
  ServiceProvider(
    id: 7,
    userId: 'user_007',
    name: 'Ruwan Silva',
    phoneNo: '+94 72 987 6543',
    email: 'ruwan.sitter@gmail.com',
    city: 'Gampaha', 
    role: 'Pet Sitter',
    profileImageUrl: 'https://example.com/images/ruwan_silva.jpg',
    galleryImages: [
      'https://example.com/images/sitter2_gallery_1.jpg',
      'https://example.com/images/sitter2_gallery_2.jpg',
    ],
    qualificationUrl: '',
    verificationUrl: '',
    clinicOrSalonName: 'Trusted Pet Care',
    clinicOrSalonAddress: 'Gampaha',
    aboutClinicSalon: 'Reliable pet sitting services.',
    experience: '6',
    serviceDescription: 'Feeding, walking, playtime.',
    pricingDetails: 'Daily rate: 4000 LKR',
    consultationFee: '',
    groomingServices: [],
    comfortableWith: ['Dogs', 'Cats'],
    availableTimes: 'Mon-Sat 8am-7pm',
    dislikes: '',
    rate: '4.8',
    notes: '',
  ),
  ServiceProvider(
    id: 8,
    userId: 'user_008',
    name: 'Nadeesha Fernando',
    phoneNo: '+94 77 765 4321',
    email: 'nadeesha.sitter@gmail.com',
    city: 'Galle', 
    role: 'Pet Sitter',
    profileImageUrl: 'https://example.com/images/nadeesha_fernando.jpg',
    galleryImages: [
      'https://example.com/images/sitter3_gallery_1.jpg',
      'https://example.com/images/sitter3_gallery_2.jpg',
    ],
    qualificationUrl: '',
    verificationUrl: '',
    clinicOrSalonName: 'Pet Buddy Sitters',
    clinicOrSalonAddress: 'Galle',
    aboutClinicSalon: 'Friendly and caring pet sitting.',
    experience: '3',
    serviceDescription: 'Pet walking, feeding, medication administration.',
    pricingDetails: 'Hourly rate: 900 LKR',
    consultationFee: '',
    groomingServices: [],
    comfortableWith: ['Dogs', 'Cats', 'Rabbits'],
    availableTimes: 'Mon-Fri 9am-6pm',
    dislikes: '',
    rate: '4.7',
    notes: '',
  ),
];
